blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/sMAE3Na
    about: My personal Discord server
  - name: MotionCapture Spigot page
    url: https://www.spigotmc.org/resources/342133/
    about: Official Spigot page of MotionCapture
